services:
  web:
    build:
      context: .
      dockerfile: build/docker/python/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ~/Library/Application Support/Anki2/jake/collection.anki2:/code/anki_database/collection.anki2
      -
    ports:
      - "8000:8000"
    env_file:
      .env
    networks:
      - portfolio

networks:
  portfolio