services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=portfolio
      - POSTGRES_USER=root_user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=abcdef
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DJANGO_SETTINGS_MODULE=portfolio_site.settings.development
      - POSTGRES_DB=portfolio
      - POSTGRES_USER=root_user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data: