services:
  web:
    build:
      context: .
      dockerfile: ./build/docker/python/Dockerfile
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      .env
    networks:
      - portfolio
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - portfolio

networks:
  portfolio:
    driver: bridge