# Generated by Django 5.0.7 on 2024-09-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link_to_deck', models.URLField(max_length=500)),
                ('initial_upload', models.DateTimeField(auto_now_add=True)),
                ('most_recent_upload', models.DateTimeField(blank=True, null=True)),
                ('number_of_uploads', models.IntegerField(default=0)),
            ],
        ),
    ]
