# Generated by Django 5.0.7 on 2024-07-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_for_skills_section',
            field=models.BooleanField(default=False),
        ),
    ]
