# Generated by Django 5.0.7 on 2024-09-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_for_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='for_portfolio',
            new_name='is_for_portfolio_section',
        ),
    ]
