name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/portfolio"
          docker build -f build/docker/python/Dockerfile -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/portfolio"
            docker pull $IMAGE_NAME:latest
            docker stop portfolio 2>/dev/null || true
            docker rm portfolio 2>/dev/null || true
            docker run -d --name portfolio -p 8000:8000 \
              -e DJANGO_ENV=production \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }}
              -e ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
              $IMAGE_NAME:latest
