name: Django CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_API }} >> 'EOF'
            set -e
            APP_DIR="/data/app"
           
            if [ ! -d "$APP_DIR" ]; then
              mkdir -p "$APP_DIR"
            fi
          
            cd "$APP_DIR"
          
            echo "So far, so good..."
