name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/portfolio"
          docker build --platform linux/arm64 -f build/docker/python/Dockerfile -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Deploy to production
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull my-docker-repo/my-django-app:latest
            docker stop django-app || true
            docker rm django-app || true
            docker run -d --name django-app -p 8000:8000 my-docker-repo/my-django-app:latest