name: Django CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio_site:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio_site:latest
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup SSH
#        uses: webfactory/ssh-agent@v0.9.0
#        with:
#          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
#
#      - name: Deploy to EC2
#        run: |
#          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_API }} >> 'EOF'
#            set -e
#            APP_DIR="/data/app"
#
#            if [ ! -d "$APP_DIR" ]; then
#              sudo mkdir -p "$APP_DIR"
#              sudo chown -R ec2-user:ec2-user "$APP_DIR"
#            fi
#
#            cd "$APP_DIR"
#
#            if [ ! -d ".git" ]; then
#              git clone https://github.com/jakegodsall/ .
#            fi
            
