name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: jakegodsall-portfolio

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
            ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
              APP_DIR="/data"
              cd "$APP_DIR"
              # Clone the repository if not already present
              if [ ! -d ".git" ]; then
                git clone https://github.com/your-username/your-repo.git .
              fi
  
              # Pull the latest changes
              git reset --hard  # Reset any local changes
              git clean -fd     # Remove untracked files
              git pull origin main
  
              # Build and run the app with Docker Compose
              docker-compose down || true  # Stop existing containers
              docker-compose up --build -d
            EOF